# Generated by Django 2.2 on 2020-09-12 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('closed', 'closed'), ('opened', 'opened'), ('pending', 'pending')], max_length=200)),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher_app.Candidate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher_app.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_matched', models.DateTimeField(default=django.utils.timezone.now, max_length=60)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher_app.Candidate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher_app.Job')),
            ],
            options={
                'ordering': ['-time_matched'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_liked', models.DateTimeField(default=django.utils.timezone.now, max_length=60)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher_app.Candidate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher_app.Job')),
            ],
            options={
                'ordering': ['-time_liked'],
            },
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_disliked', models.DateTimeField(default=django.utils.timezone.now, max_length=60)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher_app.Candidate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher_app.Job')),
            ],
            options={
                'ordering': ['-time_disliked'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(to='matcher_app.Skill'),
        ),
    ]
